name: pr-name-linter

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          title-regex: '^(chore|fix|feat|ci|refactor)!? ?:'
