name: Release Production on release

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  CI: true
on:
  release:
    types: [released]

jobs:
  pullrequest-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.3.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version-file: .nvmrc
      - name: npm install
        working-directory: . # use the root directory
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: deploy backend
        env:
          AMPT_API_KEY: ${{ secrets.AMPT_API_KEY }}
        id: deploy-backend
        working-directory: . # use the root directory
        run: |
          url=$(./scripts/deployAndGetUrl.sh prod)
          echo aha $url
          echo "BACKEND_URL=$url" >> "$GITHUB_OUTPUT"

      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: PUBLIC_BACKEND_URL=${{ steps.deploy-backend.outputs.BACKEND_URL}} PUBLIC_STAGE=prod npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy-frontend
        run: |
          url=$(npx vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "FRONTEND_URL=$url" >> "$GITHUB_OUTPUT"
