name: Release Bata on commit to main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  CI: true
on:
  push:
    branches: [main]

jobs:
  pullrequest-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.3.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version-file: .nvmrc
      - name: npm install
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy-frontend
        run: |
          url=$(npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "FRONTEND_URL=$url" >> "$GITHUB_OUTPUT"
      - name: set vercal beta alias
        run: npx vercel alias ${{ steps.deploy-frontend.outputs.FRONTEND_URL}} beta.lists.pink --token ${{ secrets.VERCEL_TOKEN }}
